apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
spec:
  secretName: certificate
  duration: 8760h # 365d
  renewBefore: 2160h # 90d
  subject:
    organizations:
    - builder
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  - client auth
  dnsNames:
  - registry.builder.svc.cluster.local
  issuerRef:
    name: issuer
    kind: Issuer
    group: cert-manager.io
