apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry
spec:
  secretName: certificate-registry
  duration: 8760h # 365d
  renewBefore: 2160h # 90d
  subject:
    organizations:
    - builder
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  - client auth
  dnsNames:
  - registry.cloud.localhost
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: issuer
