apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud

bases:
- ../../bases/registry

patches:
- registry.yaml

resources:
- certificates.yaml
- ingress.yaml
- issuer.yaml
- namespace.yaml
